version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: muse
      POSTGRES_PASSWORD: muse
    ports: 
      - '5432:5432'
    volumes:
      - muse-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - muse-redis:/var/lib/redis/data

  muse:
    build:
      context: .
    volumes:
      - ./muse:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - muse
    ports:
      - '8020:8020'

volumes:
  muse-postgres:
  muse-redis:
